
codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "15...100"

  status:
    project:
      default:
        # Do not fail when code coverage decreases
        threshold: 100
    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

  ignore:
    - "vendor/.*"
    - "**/*_test.go"
    - "**/*.yml"
    - "**/*.sh"
    - "Makefile"